export const GET_REPOS_BY_USERNAME = "@@repos/GET_REPOS_BY_USERNAME";
export const GET_REPOS_BY_USERNAME_SUCCESS =
  "@@repos/GET_REPOS_BY_USERNAME_SUCCESS";
export const GET_REPOS_BY_USERNAME_FAILED =
  "@@repos/GET_REPOS_BY_USERNAME_FAILED";
